runtime: nodejs16
service: test-node-app
main: node index.js 
vpc_access_connector:
 name: projects/glueops-13-production/locations/us-central1/connectors/vpc-access-connector
 egress_setting: all-traffic
env_variables:
